name: Liquibase Rollback

on:
  workflow_dispatch:
    inputs:
      rollback-tag:
        description: 'Rollback to a specific tag'
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:

  update:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::182571449491:role/github-rds-test-role
        # 🔼 This requires the target AWS account to be configured with GitHub's OIDC provider
        # Instructions: https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services
        aws-region: us-east-1

    - name: get database credentials
      id: secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          DB, rds!cluster-7ad2c9f7-8dbb-47fe-9fe7-b13e4469d90d
        parse-json-secrets: true
        # 🔼 This creates environment variables for each secret using provided prefix (e.g. DB_USERNAME and DB_PASSWORD)

    - name: run Liquibase rollback
      uses: liquibase-github-actions/rollback@v4.31.1
      with:
          changelogFile: "src/db-changelog.yaml"
          tag: ${{ github.event.inputs.rollback-tag }}
          url: "jdbc:postgresql://testdb-instance-1.cpggu2uyg5g0.us-east-1.rds.amazonaws.com:5432/postgres"
          username: ${{env.DB_USERNAME}}
          password: ${{env.DB_PASSWORD}}



