name: Liquibase Update

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

permissions:
  id-token: write
  contents: read

jobs:

  update:

    runs-on: ubuntu-latest

    env:
      DB_URL: "jdbc:postgresql://testdb-instance-1.cpggu2uyg5g0.us-east-1.rds.amazonaws.com:5432/postgres"

    steps:
    - uses: actions/checkout@v3

    - name: configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        role-to-assume: arn:aws:iam::182571449491:role/github-rds-test-role
        aws-region: us-east-1

    - name: Get database credentials
      id: secrets
      uses: aws-actions/aws-secretsmanager-get-secrets@v2
      with:
        secret-ids: |
          rds!cluster-7ad2c9f7-8dbb-47fe-9fe7-b13e4469d90d
        parse-json-secrets: true
        # 🔼 This creates environment variables for each secret (e.g. USERNAME and PASSWORD)

    - uses: liquibase-github-actions/update@v4.31.1
      with:
        # The root changelog
        # string
        # Required
        changelogFile: "../src/liquibase.properties"

        # The JDBC database connection URL
        # string
        # Required
        url: $DB_URL

        # Password to use to connect to the database
        # string
        # Optional
        password: $PASSWORD

        # If set to true and any changeset in a deployment fails, then the update operation stops, and liquibase attempts to rollback all changesets just deployed. A changeset marked "fail-on-error=false" does not trigger as an error, therefore rollback-on-error will not occur. Additionally, if a changeset is not auto-rollback compliant or does not have a rollback script, then no rollback-on-error will occur for any changeset.
        # bool
        # Optional
        rollbackOnError: "true"

        # Type of update results summary to show.  Values can be "off", "summary", or "verbose".
        # string
        # Optional
        showSummary: "verbose"

        # Summary output to report update summary results. Values can be "log", "console", or "all".
        # string
        # Optional
        showSummaryOutput: "all"

        # Username to use to connect to the database
        # string
        # Optional
        username: $USERNAME